{
  "formatVersion": "1.1",
  "component": {
    "group": "com.spacer",
    "module": "sdk",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "sdk-1.9.0.aar",
          "url": "sdk-1.9.0.aar",
          "size": 320077,
          "sha512": "72dcc12e644cd80976a530b68e892361b9f2c95500ffc4d3ef7b53b005072f7990f797fa0bc5a4c0b3d1bce35ef5c1d21e46aa1538edb8bdcc7fa7534d4e34b2",
          "sha256": "83aaaa3dc656b4e8a279c0c21c35a2d820bd0740b7f8692acb98d98e03e4a192",
          "sha1": "02d8131fcd3905e9fe2c53e5aa5f84352c516d90",
          "md5": "9fd156e1b648ab5017c7c1eeeb9e8d19"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.9.0.aar",
          "url": "sdk-1.9.0.aar",
          "size": 320077,
          "sha512": "72dcc12e644cd80976a530b68e892361b9f2c95500ffc4d3ef7b53b005072f7990f797fa0bc5a4c0b3d1bce35ef5c1d21e46aa1538edb8bdcc7fa7534d4e34b2",
          "sha256": "83aaaa3dc656b4e8a279c0c21c35a2d820bd0740b7f8692acb98d98e03e4a192",
          "sha1": "02d8131fcd3905e9fe2c53e5aa5f84352c516d90",
          "md5": "9fd156e1b648ab5017c7c1eeeb9e8d19"
        }
      ]
    }
  ]
}
