{
  "formatVersion": "1.1",
  "component": {
    "group": "com.spacer",
    "module": "sdk",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "sdk-2.0.0.aar",
          "url": "sdk-2.0.0.aar",
          "size": 326678,
          "sha512": "cb1154d04fa121ae2bcb246a10443bad97e2e7ca31374749d33da32d25b1e4dc3f7f0c152440b75c3c8bca90741a5fe25352001059df2e348b699dafeefe462a",
          "sha256": "d6d5c597074d621e949deb122dc1804e864d3008073f60a7a6685c524f994832",
          "sha1": "08f18c2603db4a0a0a2df36904068ca5f39b7318",
          "md5": "4ec51b285a93c548fd72dc5eec6fbd6e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-2.0.0.aar",
          "url": "sdk-2.0.0.aar",
          "size": 326678,
          "sha512": "cb1154d04fa121ae2bcb246a10443bad97e2e7ca31374749d33da32d25b1e4dc3f7f0c152440b75c3c8bca90741a5fe25352001059df2e348b699dafeefe462a",
          "sha256": "d6d5c597074d621e949deb122dc1804e864d3008073f60a7a6685c524f994832",
          "sha1": "08f18c2603db4a0a0a2df36904068ca5f39b7318",
          "md5": "4ec51b285a93c548fd72dc5eec6fbd6e"
        }
      ]
    }
  ]
}
