{
  "formatVersion": "1.1",
  "component": {
    "group": "com.spacer",
    "module": "sdk",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "sdk-2.0.0.aar",
          "url": "sdk-2.0.0.aar",
          "size": 326190,
          "sha512": "26c78bfe9ce1997095878213c6821b4f5af935dee55dd13a89895b023fb942d24b6fbff9532b9e616e8f0348d4261a091035692966b57ac5efaaec1201a4b4ec",
          "sha256": "ec6e38ef58a271e7dc6f51dc7518d6faeb2692daf4ed7780125cf57328471d4c",
          "sha1": "2ec4578053b80ddcfa411c56b4c3587563b56717",
          "md5": "baa7336ee3cfb2bc228e9e16e2637155"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-2.0.0.aar",
          "url": "sdk-2.0.0.aar",
          "size": 326190,
          "sha512": "26c78bfe9ce1997095878213c6821b4f5af935dee55dd13a89895b023fb942d24b6fbff9532b9e616e8f0348d4261a091035692966b57ac5efaaec1201a4b4ec",
          "sha256": "ec6e38ef58a271e7dc6f51dc7518d6faeb2692daf4ed7780125cf57328471d4c",
          "sha1": "2ec4578053b80ddcfa411c56b4c3587563b56717",
          "md5": "baa7336ee3cfb2bc228e9e16e2637155"
        }
      ]
    }
  ]
}
