{
  "formatVersion": "1.1",
  "component": {
    "group": "com.spacer",
    "module": "sdk",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "sdk-2.0.0.aar",
          "url": "sdk-2.0.0.aar",
          "size": 326283,
          "sha512": "467612550932a4b2fcc596d5b4e21ec545c30b1dcc204a151bbe4c32a8e343136b8bad700152e343d2a3630847589cd064f863a410b3c16afa61e3cfbd526112",
          "sha256": "2ccca7fb1987db20e0a8c600d278f40516a5e6c5f24814247ce1538276fc6932",
          "sha1": "1505966b8d8734a410fd71eb278937afcdaba5a9",
          "md5": "c590dae73907bc2347074d8ebf9072bd"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "18.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-2.0.0.aar",
          "url": "sdk-2.0.0.aar",
          "size": 326283,
          "sha512": "467612550932a4b2fcc596d5b4e21ec545c30b1dcc204a151bbe4c32a8e343136b8bad700152e343d2a3630847589cd064f863a410b3c16afa61e3cfbd526112",
          "sha256": "2ccca7fb1987db20e0a8c600d278f40516a5e6c5f24814247ce1538276fc6932",
          "sha1": "1505966b8d8734a410fd71eb278937afcdaba5a9",
          "md5": "c590dae73907bc2347074d8ebf9072bd"
        }
      ]
    }
  ]
}
